site_name: SpiCE Corpus
nav:
    - Home: index.md
    - Corpus Design: design.md
    - Transcription: transcription.md
    - Download SpiCE!: download.md
    - Research: research.md
theme: readthedocs
navigation_depth: 5
extra_css: [extra.css]
