site_name: SpiCE Corpus
nav:
    - About: index.md
    - Corpus Design: design.md
    - Transcription: transcription.md
    - Download SpiCE!: download.md
    - Research: research.md
theme: readthedocs